#konsola h2: localhost:8080/h2-console
spring:
  datasource:    
    url: jdbc:h2:mem:jcountant;DATABASE_TO_UPPER=false
    username: tomek
    password: pass1
    driver-class-name: org.h2.Driver
  jpa:  
    show-sql: true
    defer-datasource-initialization: true
    hibernate:          
      ddl-auto: create-drop
  sql:
    init:
      mode: always
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/master.xml
    contexts: dev
  h2:
    console:      
      enabled: true
  security:
    user:
      name: admin
      password: pass1

