spring:
  datasource:    
#    url: jdbc:postgresql://localhost:5432/jcountant?stringtype=unspecified
    url: jdbc:postgresql://db:5432/jcountant?stringtype=unspecified
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml
    contexts: all, postgres
  jackson:
    serialization:
      fail-on-empty-beans: false      
  h2:
    console:      
      enabled: false
 