#konsola h2: localhost:8080/h2-console
spring:
  datasource:    
    url: jdbc:h2:mem:jcountant;DATABASE_TO_UPPER=false
    username: tomek
    password: pass1
    driver-class-name: org.h2.Driver
  jpa:        
    show-sql: true
    defer-datasource-initialization: false
    hibernate:          
      ddl-auto: none
  sql:
    init:
      mode: never
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml
    contexts: all, h2
    driver-class-name: h2
  h2:
    console:      
      enabled: true
  security:
    user:
      name: admin
      password: pass1
      
  jackson:
    serialization:
      fail-on-empty-beans: false
   
